version:  '3.2'
services:
  redis:
    image: "redis:latest"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - data-redis:/data
    ports:
      - "6379:6379"
volumes:
  data-redis: